import duckdb
con = duckdb.connect("ask_your_data.db")
print("=== FACT_ORDERS (5 rows) ===")
print(con.execute("SELECT * FROM mart.fact_orders LIMIT 5").fetchdf())
print("\n=== FACT_ORDER_ITEMS (5 rows) ===")
print(con.execute("SELECT * FROM mart.fact_order_items LIMIT 5").fetchdf())
print("\n=== DIM_CUSTOMERS (5 rows) ===")
print(con.execute("SELECT * FROM mart.dim_customers LIMIT 5").fetchdf())
print("\n=== DIM_PRODUCTS (5 rows with English names) ===")
print(con.execute("SELECT product_id, product_category_name, product_category_name_english FROM mart.dim_products LIMIT 5").fetchdf())
print("\n=== DIM_SELLERS (5 rows) ===")
print(con.execute("SELECT * FROM mart.dim_sellers LIMIT 5").fetchdf())
con.close()